// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXz2AbsQ51z0Di_EacF2FnPbNKERgO9cs',
    appId: '1:974705252041:web:2128bd219f1e7ba06a1f18',
    messagingSenderId: '974705252041',
    projectId: 'whatsapp-messangr',
    authDomain: 'whatsapp-messangr.firebaseapp.com',
    storageBucket: 'whatsapp-messangr.appspot.com',
    measurementId: 'G-8GVR6KN2Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv0S-Bz7ZxtaUMwQb1qP5Ki7k0VzcYgxg',
    appId: '1:974705252041:android:66d402c42a53c2076a1f18',
    messagingSenderId: '974705252041',
    projectId: 'whatsapp-messangr',
    storageBucket: 'whatsapp-messangr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCPugluC8oB41X_fCxq8ekfhXG4jjVG1w',
    appId: '1:974705252041:ios:7e4cf713587397d06a1f18',
    messagingSenderId: '974705252041',
    projectId: 'whatsapp-messangr',
    storageBucket: 'whatsapp-messangr.appspot.com',
    iosClientId: '974705252041-6lnlkodvkkuui3sn74bmhke760r0hvi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCPugluC8oB41X_fCxq8ekfhXG4jjVG1w',
    appId: '1:974705252041:ios:7e4cf713587397d06a1f18',
    messagingSenderId: '974705252041',
    projectId: 'whatsapp-messangr',
    storageBucket: 'whatsapp-messangr.appspot.com',
    iosClientId: '974705252041-6lnlkodvkkuui3sn74bmhke760r0hvi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappme',
  );
}
